default: &default
  DB_HOST: "db"
  DB_PORT: "5432"
  USERNAME: "postgres"
  MAILER_DEFAULT_HOST: "localhost"
  MAILER_DEFAULT_PORT: "3000"
  MAILER_SENDER: "Test <noreply@nimbl3.co>"
  LINE_CHANNEL_ID: '1546867226'
  LINE_CHANNEL_SECRET: 'c2354433ef6deb107be15cca69eef101'
  LINE_CHANNEL_TOKEN: 'dLQOTC/n6AqAnlW2rpBxd7GlnCJRLC824OJrTuuFhR7P1IsFTvNcjfwxyKUvpXInp6s3eyLB6xhbKyK40nlt9wyfdtL7hBsLLqoMGDyP0C1q8xZBfpfEEoNiBRqQe17LSBWGp/6MsjqMeUFa+PVE9gdB04t89/1O/w1cDnyilFU='
  WIT_APP_ID: '5a0e8c67-d7e9-4cab-b652-fe64826eefb8'
  WIT_SERVER_ACCESS_TOKEN: 'GZ45C5Z3UQB44ROWEKPYPLAJ6YVCEBUZ'
  WIT_CLIENT_ACCESS_TOKEN: 'QLNSAAZJJ6HQ4YY5EKUEH6LT737C7BSW'

development:
  <<: *default
  DB_NAME: "rp-line-chatbot_development"
  SECRET_KEY_BASE: "#{secret_key_base}"

test:
  <<: *default
  DB_NAME: "rp-line-chatbot_test"
  SECRET_KEY_BASE: "#{secret_key_base}"
